In [ ]:
#Задание 1. Я зашла на платформу colab(https://colab.research.google.com/) под моим google-аккаунтом.

In [ ]:
#Задание 2. Новая запись (New Notebook) из меню File создана.

In [ ]:
#Задание 3. Проверить работу на примере выполнения любой печати строки командой print(‘hi’).

print('hi')

hi


In [ ]:
#Задание 4. Решить следующие задачи:
#a.Импортировать библиотеку NumPy

import numpy as np

In [ ]:
#b.Создать массив из 10 нулей

import numpy as np
b = np.zeros(10)
print(b)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#c.Создать массив из 10 единиц

import numpy as np
c = np.ones(10)
print(c)


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
#d.Создать массив из 10 пятерок

import numpy as np
d = np.full(10, 5)
print(d)



[5 5 5 5 5 5 5 5 5 5]


In [ ]:
#e.Создать массив из целых чисел от 10 до 50

import numpy as np
e = np.arange(10,51)
print(e)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [ ]:
#f.Создать массив из четных чисел от 10 до 50

import numpy as np
f = np.arange(10,51,2)
print(f)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:
#g.Создать матрицу 3х3 с числами от 0 до 8

import numpy as np
g = np.arange(9).reshape(3,3)
print(g)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#h.Создать единичную матрицу 3x3

import numpy as np
g = np.eye(3).reshape(3,3)
print(g)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#i.Использовать NumPy для генерации случайного числа от 0 до 1

import numpy as np
  
x=np.random.random(1)[0]
print(x)

0.3848068002623445


In [ ]:
#j.Использовать NumPy для генерации массива из 25 случайных чисел,взятых из стандартного нормального распределения

import numpy as np
rand_num = np.random.normal(0,1,25)
print("25 random numbers from a standard normal distribution:")
print(rand_num)

25 random numbers from a standard normal distribution:
[ 0.21312301  0.083404   -1.22542806  0.09009282  1.13453958 -1.00233521
 -0.93797024  0.33878593  0.94978507  1.54371354 -0.05734324  2.12854849
  0.34875159 -0.04063733 -1.09865458 -0.05023083 -0.20385225 -0.11607766
 -0.58449219  0.64880798 -0.31818761  1.30754184  1.60110178 -0.73274428
 -0.49372273]


In [ ]:
#k.Создать следующую матрицу используя функции библиотеки NumPy:

import numpy as np
arr = np.arange(0.01, 1.01, 0.01)
arr = arr.reshape(10,10)
print(arr)


[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [ ]:
#l.Дана стартовая матрица.Эта матрица будет использоваться в последующих задачах:

import numpy as np

mat = np.arange(1,26).reshape(5,5)
print(mat)
print('-------------------')
x = (mat[2:,1:]) 
np.reshape(x,(3,4))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
-------------------


array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
#m.Написать код обращения к элементу, который вернет значение  20 из стартовой матрицы задачи l

import numpy as np

mat = np.arange(1,26).reshape(5,5)
print(mat)
print('-------------------')
print(mat[:4])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
-------------------
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [ ]:
#n.Написать код к стартовой матрице задачи l , который воспроизводит вывод, показанный ниже
#array([[2],
#       [7],
#       [12]])

import numpy as np

mat = np.arange(1,26).reshape(5,5)
print(mat)
print('-------------------')
x = (mat[:3,1])
np.reshape(x,(3,1))



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
-------------------


array([[ 2],
       [ 7],
       [12]])

In [ ]:
#o.Написать код к стартовой матрице задачи l , который воспроизводит вывод, показанный ниже

#array([21,22,23,24,25])

import numpy as np

mat = np.arange(1,26).reshape(5,5)
print(mat)
print('-------------------')
x = (mat[4])
np.reshape(x,(1,5))



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
-------------------


array([[21, 22, 23, 24, 25]])

In [ ]:
#p.Написать код к стартовой матрице задачи l , который воспроизводит вывод, показанный ниже
#array([[16,17,18,19,20],
       #[21,22.23,24,25]])

import numpy as np

mat = np.arange(1,26).reshape(5,5)
print(mat)
print('-------------------')
x = (mat[3:])
np.reshape(x,(2,5))     
     

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
-------------------


array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
#q.Получить сумму всех значений в стартовой матрице mat

import numpy as np

mat = np.arange(1,26).reshape(5,5)
print(mat)
print('-------------------')
print(mat.sum())

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
-------------------
325


In [ ]:
#r.Получить стандартное отклонение в стартовой матрице mat

import numpy as np

mat = np.arange(1,26).reshape(5,5)
print(mat)
print('-------------------')
result = np.std(mat)
print('SD:', result)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
-------------------
SD: 7.211102550927978


In [ ]:
#s.Получить сумму значений в колонках в стартовой матрице mat


import numpy as np

mat = np.arange(1,26).reshape(5,5)
print(mat)
print('-------------------')
# To sum over columns:
print('To sum over columns:',(mat.sum(axis=0)))
print('--------------------')
# Or, to sum over rows:
print('Or, to sum over rows:',(mat.sum(axis=1)))



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
-------------------
To sum over columns: [55 60 65 70 75]
--------------------
Or, to sum over rows: [ 15  40  65  90 115]


In [1]:
#Код, который написать, нужно сохранить в виде файла с именем "Numpy_solutions.ipynb" в моем личном репозитории на GitHub




